### PR TITLE
Create notebooks for Graph Coloring Problem

### PR DESCRIPTION
**Pull request by kotarot**
Hi,

I created example notebooks for Graph Coloring Problem. Would you please review it?

Thanks!
Kotaro

### CODE REVIEW

**Comment by kotarotanahashi** [comment]
@kotarot It looks like a test for notebooks in Python 3.7 failed. Could you fix the problem?

**Comment by kotarot** [comment]
@kotarotanahashi Sorry for my huge delay.

> It looks like a test for notebooks in Python 3.7 failed. Could you fix the problem?

Yes, I was trying to do so, but I checked the error log carefully and found that the problem is caused by IPython kernel issue.

We see error logs like
`zmq.error.ZMQError: Address already in use`
and
`RuntimeError: Kernel died before replying to kernel_info`
(full Traceback below).

Note that we had the same error in a recent CI test as in https://circleci.com/gh/recruit-communications/pyqubo/444 .

Can you just restart the test for Python 3.7, please?

---
Full Traceback

```
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/circleci/repo/env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/circleci/repo/env/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/circleci/repo/env/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/circleci/repo/env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 467, in initialize
    self.init_sockets()
  File "/home/circleci/repo/env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 260, in init_sockets
    self.init_iopub(context)
  File "/home/circleci/repo/env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 265, in init_iopub
    self.iopub_port = self._bind_socket(self.iopub_socket, self.iopub_port)
  File "/home/circleci/repo/env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 181, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "/home/circleci/repo/env/bin/runipy", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/repo/env/lib/python3.7/site-packages/runipy/main.py", line 153, in main
    nb, args.pylab, args.matplotlib, profile_dir, working_dir
  File "/home/circleci/repo/env/lib/python3.7/site-packages/runipy/notebook_runner.py", line 106, in __init__
    self.kc.wait_for_ready()
  File "/home/circleci/repo/env/lib/python3.7/site-packages/jupyter_client/blocking/client.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by kotarot** [comment]
Oh, we needed to rebase this branch with (or merge it from) master first, because we had a library version problems. I'm gonna work on it.

**Comment by kotarot** [comment]
We didn't need to restart the test because of the new commit.

@kotarotanahashi Can you check above?

**Comment by kotarotanahashi** [comment]
@kotarot 
> Note that we had the same error in a recent CI test as in https://circleci.com/gh/recruit- communications/pyqubo/444 .
> (so this means this kind of error sporadically occurs in CI tests, and it can be another issue, I think.)
Yes, this issue should be fixed too.

> We didn't need to restart the test because of the new commit.
Thank you! When you are ready to merge, please push the latest code to this pull request.

**Comment by kotarot** [comment]
@kotarotanahashi 
Thanks for cheking it!
I've pulled the latest code from master by `git merge master` in this commit https://github.com/recruit-communications/pyqubo/pull/30/commits/839437b68bbf4ff4dc819c8f1c0537857e559182 . Should I rebase the branch rather than merging?

**Comment by kotarotanahashi** [comment]
@kotarot 
> Should I rebase the branch rather than merging?

I don't have any preference.  Just merging is fine.

**Comment by kotarot** [comment]
@kotarotanahashi 
I've already merged the latest codes to this branch and pushed it last night ( https://github.com/recruit-communications/pyqubo/commit/839437b68bbf4ff4dc819c8f1c0537857e559182 ). Is that all right?

**Comment by kotarot** [comment]
@kotarotanahashi Thanks for your review and merging it!

**Pull request merged**
